- name: Create new user on master server
  hosts: all
  become: yes
  tasks:
    - name: Ensure '{{ new_username }}' group exists
      ansible.builtin.group:
        name: "{{ new_username }}"
        state: present

    - name: Create the user '{{ new_username }}' with password and shell
      ansible.builtin.user:
        name: "{{ new_username }}"
        password: "{{ user_password | password_hash('sha512') }}"
        groups: "{{ new_username }}"
        shell: /bin/bash
        state: present

    - name: Create the file for user '{{ new_username }}' with content
      # CHANGE 1: Use the 'ansible.builtin.copy' module instead of 'ansible.builtin.file'
      ansible.builtin.copy:
        # CHANGE 2: 'path' is usually called 'dest' in the copy module, 
        # but 'path' is aliased and works. Using 'dest' for clarity.
        dest: "/home/{{ new_username }}/don" 
        state: file                                   # Use 'file' state if needed, though 'copy' implies it
        owner: "{{ new_username }}"
        group: "{{ new_username }}"
        mode: '0644'
        content: "this just trial via jenkins we can assign the playbook task or not trigger from github"
